Repository IBM/ibm-secretshare-operator, pull requests merged in 2020-08, with the labels that each got.

#15 replace base image
  Dockerfile
Labels: approved, lgtm, size/XS

#17 use ubi as base image
  .gitignore
  Dockerfile
Labels: approved, lgtm, size/XS

#18 update golang version to fix vulnerabilities
  Dockerfile
Labels: approved, lgtm, size/XS

#19 fetch secretshare instance before updating the status of the CR
  controllers/secretshare_controller.go
Labels: approved, lgtm, size/S

#20 Fix build multi arch issue
  Makefile
  common/scripts/multiarch_image.sh
Labels: approved, lgtm, size/S

#21 Update instance status update
  Dockerfile
  api/v1/secretshare_types.go
  controllers/secretshare_controller.go
Labels: approved, lgtm, size/M

#22 add licenses
  Dockerfile
Labels: approved, lgtm, size/XS

#23 fix multi arch image
  Dockerfile
  Makefile
Labels: approved, lgtm, size/XS

#24 fix secret cm update issue
  config/crd/bases/ibmcpcs.ibm.com_secretshares.yaml
  controllers/configmap.go
  controllers/secret.go
Labels: approved, lgtm, size/M
