Repository IBM/ibm-secretshare-operator, pull requests merged in 2020-09, with the labels that each got.

#25 fix typo
  Dockerfile
  api/v1/secretshare_types.go
  controllers/namespace.go
Labels: approved, lgtm, size/XS

#26 bump the image version to 1.2.1
  version/version.go
Labels: approved, lgtm, size/XS

#27 [Do not merge] remove owner reference
  OWNERS
  controllers/configmap.go
  controllers/secret.go
  controllers/secretshare_controller.go
  version/version.go
Labels: approved, lgtm, size/L

#28 remove secret/cm watching and add regards requeue
  controllers/configmap.go
  controllers/secret.go
  controllers/secretshare_controller.go
  controllers/subscription.go
  hack/boilerplate.go.txt
  main.go
Labels: approved, lgtm, size/M
