Repository IBM/ibm-secretshare-operator, pull requests merged in 2021-01, with the labels that each got.

#33 update copyright for 2021
  Makefile
  api/v1/groupversion_info.go
  api/v1/secretshare_types.go
  api/v1/zz_generated.deepcopy.go
  common/Makefile.common.mk
  common/scripts/.githooks/make_lint-all.sh
  common/scripts/.githooks/pre-commit
  common/scripts/codecov.sh
  common/scripts/config_docker.sh
  common/scripts/create_bundle.sh
  common/scripts/gobuild.sh
  common/scripts/install-operator-sdk.sh
  common/scripts/lint_copyright_banner.sh
  common/scripts/lint_go.sh
  common/scripts/multiarch_image.sh
  common/scripts/push-csv.sh
  controllers/configmap.go
  controllers/constant.go
  controllers/namespace.go
  controllers/secret.go
  controllers/secretshare_controller.go
  controllers/subscription.go
  controllers/suite_test.go
  hack/boilerplate.go.txt
  main.go
  version/version.go
Labels: approved, lgtm, size/M

#34 added bitscuit to OWNERS
  OWNERS
Labels: approved, lgtm, size/XS

#35 bump the version in the CSV
  bundle/manifests/ibm-secretshare-operator.clusterserviceversion.yaml
Labels: approved, lgtm, size/XS

#36 updated UBI image for EUS version
  Dockerfile
  Makefile
  bundle/manifests/ibm-secretshare-operator.clusterserviceversion.yaml
  version/version.go
Labels: approved, lgtm, size/S

#37 updated gogo/protobuf module to v1.3.2 to fix CVE-2021-3121
  go.mod
  go.sum
Labels: approved, lgtm, size/M

#38 Porting protobuf vulnerability fix to EUS
  go.mod
  go.sum
Labels: approved, lgtm, size/M

#39 [hold] compare before update && don't update management ingress config
  controllers/configmap.go
  controllers/secret.go
Labels: approved, lgtm, size/S
