Repository IBM/ibm-secretshare-operator, pull requests merged in 2021-09, with the labels that each got.

#69 sync up future branch with master branch
  Dockerfile
  Makefile
  base_images.json
  bundle/manifests/ibm-secretshare-operator.clusterserviceversion.yaml
  common/scripts/config_docker.sh
  config/crd/bases/ibmcpcs.ibm.com_secretshares.yaml
  config/manifests/bases/ibm-secretshare-operator.clusterserviceversion.yaml
  version/version.go
Labels: approved, size/M, lgtm

#71 bump version to 1.9.0
  bundle/manifests/ibm-secretshare-operator.clusterserviceversion.yaml
  version/version.go
Labels: approved, size/XS, lgtm

#72 subsciption not in the map
  api/v1/zz_generated.deepcopy.go
  controllers/secretshare_controller.go
  controllers/subscription.go
  go.sum
Labels: approved, size/M, lgtm

#73 Update README.md
  README.md
Labels: approved, size/XS, lgtm, ok-to-test
