Repository IBM/ibm-secretshare-operator, pull requests merged in 2022-01, with the labels that each got.

#91 refactor labels
  controllers/configmap.go
  controllers/secret.go
  controllers/secretshare_controller.go
Labels: approved, lgtm, size/S

#93 Update Copyright to 2022
  Makefile
  api/v1/groupversion_info.go
  api/v1/secretshare_types.go
  api/v1/zz_generated.deepcopy.go
  common/Makefile.common.mk
  common/scripts/.githooks/make_lint-all.sh
  common/scripts/config_docker.sh
  common/scripts/create_bundle.sh
  common/scripts/gobuild.sh
  common/scripts/install-operator-sdk.sh
  common/scripts/lint_copyright_banner.sh
  common/scripts/lint_go.sh
  common/scripts/multiarch_image.sh
  common/scripts/next-csv.sh
  common/scripts/push-csv.sh
  controllers/configmap.go
  controllers/constant.go
  controllers/namespace.go
  controllers/secret.go
  controllers/secretshare_controller.go
  controllers/subscription.go
  controllers/suite_test.go
  hack/boilerplate.go.txt
  main.go
  version/version.go
Labels: approved, size/M, lgtm

#92 Update Copyright to 2022
  Makefile
  api/v1/groupversion_info.go
  api/v1/secretshare_types.go
  api/v1/zz_generated.deepcopy.go
  common/Makefile.common.mk
  common/scripts/.githooks/make_lint-all.sh
  common/scripts/codecov.sh
  common/scripts/config_docker.sh
  common/scripts/create_bundle.sh
  common/scripts/gobuild.sh
  common/scripts/install-operator-sdk.sh
  common/scripts/lint_copyright_banner.sh
  common/scripts/lint_go.sh
  common/scripts/multiarch_image.sh
  common/scripts/next-csv.sh
  common/scripts/push-csv.sh
  controllers/configmap.go
  controllers/constant.go
  controllers/namespace.go
  controllers/secret.go
  controllers/secretshare_controller.go
  controllers/subscription.go
  controllers/suite_test.go
  hack/boilerplate.go.txt
  main.go
  version/version.go
Labels: approved, size/M, lgtm

#94 crypto update for CVE-2020-29652
  go.mod
  go.sum
Labels: approved, size/XS, lgtm

#95 use ss name as prefix and ns as name for label key
  controllers/configmap.go
  controllers/secret.go
  controllers/secretshare_controller.go
Labels: approved, lgtm, size/S
