Repository IBM/ibm-secretshare-operator, pull requests merged in 2022-11, with the labels that each got.

#132 added runAsNonRoot to securityContext
  bundle/manifests/ibm-secretshare-operator.clusterserviceversion.yaml
  config/manager/manager.yaml
Labels: approved, lgtm

#135 bump version for 3.19.7
  bundle/manifests/ibm-secretshare-operator.clusterserviceversion.yaml
  version/version.go
Labels: approved, size/XS, lgtm

#136 New prow cluster name
  common/Makefile.common.mk
Labels: size/XS

#137 New prow cluster name
  common/Makefile.common.mk
Labels: size/XS
