Repository IBM/ibm-secretshare-operator, pull requests merged in 2023-06, with the labels that each got.

#167 bump version for 3.19.13
  bundle/manifests/ibm-secretshare-operator.clusterserviceversion.yaml
  version/version.go
Labels: approved, size/XS, lgtm

#169 [LTSR] Update ImagePullPolicy to IfNotPresent
  bundle/manifests/ibm-secretshare-operator.clusterserviceversion.yaml
Labels: approved, size/XS, lgtm

#168 Update go to 1.20.5
  Dockerfile
Labels: approved, size/XS

#171 update apiextensions pkg
  go.mod
  go.sum
Labels: approved, lgtm, size/S
