Repository IBM/ibm-secretshare-operator, pull requests merged in 2023-07, with the labels that each got.

#172 update go, pkgs for 4.1
  Dockerfile
  go.mod
  go.sum
Labels: approved, size/M, lgtm

#173 bump version for 3.19.14
  bundle/manifests/ibm-secretshare-operator.clusterserviceversion.yaml
  version/version.go
Labels: approved, size/XS, lgtm

#174 updated dependabot to only open PRs against release-ltsr
  .github/dependabot.yml
Labels: approved, size/XS, lgtm

#176 update go, logrus for 3.19.14
  Dockerfile
  go.mod
  go.sum
Labels: approved, lgtm, size/S
